export function renderHelp(): string {
  return [
    "std-purge",
    "",
    "Aggressively cleans Shopify theme JSON templates.",
    "",
    "Usage:",
    "  std-purge [options]",
    "",
    "Options:",
    "  --path <dir>              Theme directory to clean. Defaults to the current directory.",
    "  --dry-run                 Print planned changes without writing files.",
    "  --yes                    Apply changes without interactive confirmation.",
    "  --json                   Print the cleanup report as JSON.",
    "  --keep-template <name>    Preserve an extra template JSON file. Repeat as needed.",
    "  -h, --help               Show this help message.",
    "",
    "Behavior:",
    "  Deletes non-core JSON files under templates/**/*.json.",
    "  Keeps core storefront templates and templates/customers/*.json.",
    "  Skips existing sections and .liquid templates.",
    "  Writes sections/hello-world.liquid and templates/index.json as a valid starter page.",
    "  Leaves config/settings_schema.json and config/settings_data.json alone.",
    "",
    "Examples:",
    "  std-purge --path ./theme --dry-run",
    "  std-purge --path ./theme --yes",
    "  std-purge --path ./theme --keep-template page.about"
  ].join("\n");
}
