export function renderHelp(): string {
  return [
    "std-purge",
    "",
    "Aggressively cleans Shopify theme JSON templates.",
    "",
    "Usage:",
    "  std-purge [options]",
    "",
    "Options:",
    "  -p, --path <dir>          Theme directory to clean. Defaults to the current directory.",
    "  -d, --dry-run             Print planned changes without writing files.",
    "  -w, --write               Apply changes without interactive confirmation.",
    "  -j, --json                Print the cleanup report as JSON.",
    "  -k, --keep <name>         Preserve an extra template JSON file. Repeat as needed.",
    "  -h, --help                Show this help message.",
    "",
    "Behavior:",
    "  Deletes non-core JSON files under templates/**/*.json.",
    "  Keeps core storefront templates and templates/customers/*.json.",
    "  Skips existing sections and .liquid templates.",
    "  Writes templates/index.json pointing to the custom-liquid section.",
    "  Leaves config/settings_schema.json and config/settings_data.json alone.",
    "",
    "Examples:",
    "  std-purge --path ./theme --dry-run",
    "  std-purge --path ./theme --write",
    "  std-purge --path ./theme --keep page.about"
  ].join("\n");
}
